
import React, { useState } from 'react';
import { Cloud, Save, CheckCircle, WifiOff, Copy, Terminal, Play, AlertTriangle, RefreshCw } from 'lucide-react';
import { configureSupabase, isSupabaseConfigured, disconnectSupabase, testConnection } from '../supabaseClient';

const ConfigView: React.FC = () => {
  const [url, setUrl] = useState('');
  const [key, setKey] = useState('');
  const [testStatus, setTestStatus] = useState<'idle' | 'testing' | 'success' | 'error'>('idle');
  const [errorMessage, setErrorMessage] = useState('');
  
  const isConfigured = isSupabaseConfigured();

  // Nuevo SQL corregido para evitar problemas de identidad y permisos
  const sqlCode = `
-- 1. Si ya creaste la tabla antes, bórrala para evitar conflictos (CUIDADO: Borra datos previos)
drop table if exists school_data;

-- 2. Crear la tabla con ID flexible (generated BY DEFAULT)
create table school_data (
  id bigint primary key generated by default as identity,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  data jsonb not null
);

-- 3. Configurar permisos básicos (IMPORTANTE: Esto permite leer/escribir)
alter table school_data enable row level security;
create policy "Public Access" on school_data for all using (true) with check (true);
grant all on table school_data to anon, authenticated, service_role;

-- 4. Insertar la "caja" inicial vacía donde guardaremos todo (ID 1)
insert into school_data (id, data) values (1, '{}'::jsonb);
`;

  const handleTestConnection = async (): Promise<boolean> => {
    if (!url || !key) {
        setErrorMessage('Por favor ingresa la URL y la Key primero.');
        setTestStatus('error');
        return false;
    }

    setTestStatus('testing');
    setErrorMessage('');

    try {
        const success = await testConnection(url, key);
        if (success) {
            setTestStatus('success');
            return true;
        } else {
            // Este caso es raro porque testConnection lanza throw, pero por si acaso
            setTestStatus('error');
            setErrorMessage('Error desconocido.');
            return false;
        }
    } catch (e: any) {
        setTestStatus('error');
        setErrorMessage(e.message || 'Error desconocido al conectar.');
        return false;
    }
  };

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();
    if (testStatus !== 'success') {
        // Si no han probado, forzamos la prueba
        handleTestConnection().then((success) => {
             // Si pasa la prueba, guardamos
             if (success) { 
                 configureSupabase(url, key);
                 window.location.reload();
             }
        });
        return;
    }
    
    configureSupabase(url, key);
    window.location.reload();
  };

  const handleDisconnect = () => {
    if (confirm('¿Estás seguro de desconectar la base de datos? Volverás al modo local.')) {
      disconnectSupabase();
    }
  };

  const copyToClipboard = () => {
      navigator.clipboard.writeText(sqlCode);
      alert('Código copiado al portapapeles');
  };

  return (
    <div className="p-6 md:p-8 max-w-5xl mx-auto space-y-8">
      <div className="space-y-2">
        <h2 className="text-3xl font-bold text-slate-800">Configuración de Nube</h2>
        <p className="text-slate-500">Conecta tu escuela a Supabase para sincronizar datos entre dispositivos.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Columna Izquierda: Instrucciones SQL */}
        <div className="space-y-6">
            {!isConfigured ? (
                <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6">
                    <h3 className="font-bold text-lg text-slate-800 mb-2 flex items-center text-purple-700">
                         <Terminal size={20} className="mr-2" />
                         Paso 1: Preparar Base de Datos
                    </h3>
                    <p className="text-sm text-slate-600 mb-4">
                        Copia este código y pégalo en el <strong>SQL Editor</strong> de Supabase. Luego presiona "RUN".
                        <br/>
                        <span className="text-red-500 font-bold">IMPORTANTE:</span> Este paso es obligatorio para crear la tabla.
                    </p>
                    
                    <div className="relative group">
                        <div className="absolute top-0 right-0 p-2">
                            <button 
                                onClick={copyToClipboard}
                                className="p-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-bold flex items-center shadow-lg transition-all"
                            >
                                <Copy size={14} className="mr-1" /> Copiar SQL
                            </button>
                        </div>
                        <pre className="bg-slate-900 text-green-400 p-4 pt-10 rounded-xl text-[11px] overflow-x-auto font-mono border border-slate-800 leading-relaxed">
                            {sqlCode}
                        </pre>
                    </div>
                </div>
            ) : (
                 <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6">
                    <h3 className="font-bold text-lg text-slate-800 mb-4">Estado de la Conexión</h3>
                    <div className="bg-green-50 border border-green-200 rounded-xl p-6 text-center">
                        <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                            <CheckCircle size={32} className="text-green-600" />
                        </div>
                        <h4 className="text-xl font-bold text-green-800 mb-2">Conectado a Supabase</h4>
                        <p className="text-green-700 mb-6 text-sm">Tu escuela está en línea. Los cambios se guardan automáticamente en la nube.</p>
                        <button 
                            onClick={handleDisconnect}
                            className="px-4 py-2 bg-white border border-red-200 text-red-600 rounded-lg hover:bg-red-50 text-sm font-bold transition-colors flex items-center justify-center mx-auto"
                        >
                            <WifiOff size={16} className="mr-2"/> Desconectar
                        </button>
                    </div>
                </div>
            )}
        </div>

        {/* Columna Derecha: Formulario de Conexión */}
        {!isConfigured && (
          <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 h-fit">
             <h3 className="font-bold text-lg text-slate-800 mb-4 flex items-center text-blue-700">
                <Cloud className="mr-2" size={20} /> 
                Paso 2: Conectar Aplicación
             </h3>
             
             <div className="mb-6 text-sm text-slate-600">
                Ve a <strong>Project Settings</strong> {'>'} <strong>API</strong> en Supabase y copia tus credenciales.
             </div>

             <form onSubmit={handleSave} className="space-y-4">
                <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Project URL</label>
                    <input 
                      type="text" 
                      value={url}
                      onChange={e => { setUrl(e.target.value); setTestStatus('idle'); }}
                      placeholder="https://xyz.supabase.co"
                      className="w-full px-4 py-3 border border-slate-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-sm"
                      required
                    />
                </div>
                <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">API Key (public/anon)</label>
                    <input 
                      type="password" 
                      value={key}
                      onChange={e => { setKey(e.target.value); setTestStatus('idle'); }}
                      placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI..."
                      className="w-full px-4 py-3 border border-slate-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-sm"
                      required
                    />
                </div>

                {/* Mensajes de Estado */}
                {testStatus === 'error' && (
                    <div className="p-3 bg-red-50 border border-red-100 rounded-lg text-red-600 text-xs flex items-start">
                        <AlertTriangle size={16} className="mr-2 flex-shrink-0 mt-0.5" />
                        <div>
                            <strong>Error:</strong> {errorMessage}
                        </div>
                    </div>
                )}

                {testStatus === 'success' && (
                    <div className="p-3 bg-green-50 border border-green-100 rounded-lg text-green-700 text-xs flex items-center">
                        <CheckCircle size={16} className="mr-2" />
                        <strong>¡Conexión exitosa!</strong> Puedes guardar ahora.
                    </div>
                )}

                <div className="flex gap-3 pt-2">
                    <button 
                        type="button"
                        onClick={() => handleTestConnection()}
                        disabled={testStatus === 'testing' || !url || !key}
                        className={`flex-1 py-3 font-bold rounded-xl transition-all flex items-center justify-center gap-2 text-sm
                            ${testStatus === 'testing' ? 'bg-slate-100 text-slate-400' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'}
                        `}
                    >
                        {testStatus === 'testing' ? <RefreshCw className="animate-spin" size={18}/> : <Play size={18} />}
                        {testStatus === 'testing' ? 'Probando...' : 'Probar Conexión'}
                    </button>

                    <button 
                        type="submit"
                        disabled={testStatus !== 'success'}
                        className={`flex-1 py-3 font-bold rounded-xl shadow-lg transition-all flex items-center justify-center gap-2 text-sm
                            ${testStatus === 'success' 
                                ? 'bg-blue-600 text-white hover:bg-blue-700 hover:-translate-y-0.5' 
                                : 'bg-slate-200 text-slate-400 cursor-not-allowed'}
                        `}
                    >
                        <Save size={18} /> Guardar
                    </button>
                </div>
             </form>
          </div>
        )}
      </div>
    </div>
  );
};

export default ConfigView;